# Generated by Django 4.0.5 on 2022-06-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('emp_id', models.CharField(max_length=6)),
                ('mobile', models.CharField(max_length=11)),
            ],
        ),
    ]
